### ISSUE TITLE
DexSim

### ISSUE THREAD

**Issue by ClearSimpleAndPlain** [jstevensog/wixel-sdk#11]
Hi, I'm building a rig for my niece and want to test it, but I don't have the G4 here.  I'm trying to use the dexsim program to simulate the G4.  What program do you recommend for use with dexsim?  I see there is dex-drip, dexbridge, xBridge, dexterity_wixel and radio_snifer.  Would they all work?  Right now I'm just trying to see the data from dexsim through a USB connection to my terminal program.  I've run the test_tx and test_rx on each wixel and viceversa.  The packets are getting across.

I do have 2 Wixels, and I'm very familiar with microcontrollers and computer programming.  

Thanks,
Denis.

**Comment by jstevensog** [comment]
Hi Denis,
The dexsim program is not complete.  I haven't been able to get back to it
to figure out why it doesn't work correctly.  There is no simulator in any
of these programs.  I obviously need to clean up the repo.
dex-drip is an older version of the original dexdrip wixel.  I will remove
it.
dexbridge is my original redo, and this is now deprecated.  I will remove
it.
xBridge2 is the current xBridge code and should be used, xBridge should
not.  I will remove it.
dexterity_wixel is the code that all of the dex/xBridge stuff was based
on.  I will remove it.
the rest are all standard wixel example projects, and I will leave them in
the SDK for now.

Cheers

On Wed, Dec 2, 2015 at 8:45 AM, ClearSimpleAndPlain <
notifications@github.com> wrote:

> Hi, I'm building a rig for my niece and want to test it, but I don't have
> the G4 here. I'm trying to use the dexsim program to simulate the G4. What
> program do you recommend for use with dexsim? I see there is dex-drip,
> dexbridge, xBridge, dexterity_wixel and radio_snifer. Would they all work?
> Right now I'm just trying to see the data from dexsim through a USB
> connection to my terminal program. I've run the test_tx and test_rx on each
> wixel and viceversa. The packets are getting across.
> 
> I do have 2 Wixels, and I'm very familiar with microcontrollers and
> computer programming.
> 
> Thanks,
> Denis.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jstevensog/wixel-sdk/issues/11.

## 

John Stevens
"You are how you live, not what you have."
