### ISSUE TITLE
waitDoingServices does not work with break flag

### ISSUE THREAD

**Issue by savek-cc** [jstevensog/wixel-sdk#23]
Giving the break_flag to waitDoingServices apparently doesn't have any effect - it will always wait for the full timeout. Passed by value? Passing by reference is apparently not possible with SDCC.

**Comment by jstevensog** [comment]
Hi Timm,
Yeah, I found out a while ago that this is the case.  I should really
change it.
I really want to rewrite xBridge completely soon.  It is not original code
by me and the many contributors have done a great job, but all very
differently.
All the comments in there are either from original code, or added by me as
a learned how it worked.  I am a stickler for lots of comments in open
source code.
I never assume that someone can read the code without comments to
understand what is actually going on.
So, once channel scanning capture is working and in the code, I will do a
full rewrite and change the operation to a state machine format which will
be much more efficient.
Means more global booleans and stuff, but will be much better.
Cheers

On Sun, Jun 26, 2016 at 6:12 AM, Timm Korte notifications@github.com
wrote:

> Giving the break_flag to waitDoingServices apparently doesn't have any
> effect - it will always wait for the full timeout. Passed by value? Passing
> by reference is apparently not possible with SDCC.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jstevensog/wixel-sdk/issues/23, or mute the thread
> https://github.com/notifications/unsubscribe/AIQs82n-JOh4BB5cSvJqak-ukR88qBuEks5qPYvCgaJpZM4I-a0d
> .

## 

John Stevens
"You are how you live, not what you have."

**Comment by savek-cc** [comment]
Hi John,
in my repository, I replaced the waitDoingServices function with a function macro - this now actually does resprect the break_flag and works just like the function otherwise - maybe it could be interesting for you to include 'till you get around to a rewrite ;)
Timm
P.S.: https://github.com/savek-cc/wixel-sdk/commit/5213b8b85c5fccb53a67daad464a0c22da544f38

**Comment by jstevensog** [comment]
Hi Timm,
Will definitely get this into the public code. Thanks for this. I never got around to solving that issue.
Cheers

---- Timm Korte wrote ----

**Comment by savek-cc** [comment]
Guess this issue can be closed, as you included the code in https://github.com/jstevensog/wixel-sdk/commit/477f6e1a25755683861997f66447550eab65139c
