### ISSUE TITLE
Wixel SDK make errors

### ISSUE THREAD

**Issue by garidan** [jstevensog/wixel-sdk#7]
Hi, I just downloaded your project and recompiled the wixel SDK.
I'm on OSX Yosemite and installed sdcc using brew.
I had a few errors which I "resolved", now I'm going to try if the apps so "patched" really work too :-)
I put here the errors signaled and what I did to complete the "make" process.
I wonder if you get the same problems, I'm starting clean, so everything is compiled.

---

MBP-di-Daniele:wixel-sdk dgariboldi$ make
Compiling apps/adc_test/adc_test.rel
Compiling libraries/src/radio_com/radio_com.rel
Creating libraries/lib/radio_com.lib
Compiling libraries/src/radio_link/radio_link.rel
Creating libraries/lib/radio_link.lib
Compiling libraries/src/radio_mac/radio_mac.rel
Creating libraries/lib/radio_mac.lib
Compiling libraries/src/radio_registers/radio_registers.rel
Creating libraries/lib/radio_registers.lib
Compiling libraries/src/random/random.rel
Compiling libraries/src/random/random_from_adc.rel
Compiling libraries/src/random/random_from_sernum.rel
Creating libraries/lib/random.lib
cp libraries/src/uart/core/uart.c libraries/src/uart/uart0.c
Compiling libraries/src/uart/uart0.rel
cp libraries/src/uart/core/uart.c libraries/src/uart/uart1.c
Compiling libraries/src/uart/uart1.rel
Creating libraries/lib/uart.lib
Compiling libraries/src/usb/green_led.rel
Compiling libraries/src/usb/usb.rel
Creating libraries/lib/usb.lib
Compiling libraries/src/usb_cdc_acm/usb_cdc_acm.rel
libraries/src/usb_cdc_acm/usb_cdc_acm.c:355: error 98: conflict with previous definition of 'usbComRxReceive' for attribute 'type'
from type 'void function ( const-unsigned-char xdata\* fixed, unsigned-char fixed) fixed'
  to type 'void function ( unsigned-char xdata\* fixed, unsigned-char fixed) fixed'
make: **\* [libraries/src/usb_cdc_acm/usb_cdc_acm.rel] Error 1
MBP-di-Daniele:wixel-sdk dgariboldi$ 

---

-- modified usb_cdc_acm.c to have the same signature as in usb_com.h

---

Linking apps/dexsim/dexsim.hex

?ASlink-Warning-Undefined Global '___sdcc_isdigit' referenced by module '_atof'
make: **\* [apps/dexsim/dexsim.hex] Error 1

---

-- bug http://sourceforge.net/p/sdcc/bugs/2295/ I update sdcc to  HEAD which means version 3.5.4 #9306

---

Compiling apps/dexsim/dexsim.rel
apps/dexsim/dexsim.c:752: error 226: no type specifier for '(cast)'
make: **\* [apps/dexsim/dexsim.rel] Error 1

---

-- modified memcpy(&flash_settings, (__xdata *)FLASH_SETTINGS, sizeof(flash_settings));
-- to memcpy(&flash_settings, (uint8 XDATA *) FLASH_SETTINGS, sizeof(flash_settings));

---

Compiling apps/joystick/joystick.rel
apps/joystick/joystick.c:140: error 78: incompatible types
from type 'char xdata\* xdata'
  to type 'int generic\* pdata'
apps/joystick/joystick.c:142: error 78: incompatible types
from type 'char xdata\* xdata'
  to type 'int generic\* pdata'
apps/joystick/joystick.c:144: error 78: incompatible types
from type 'char xdata\* xdata'
  to type 'int generic\* pdata'
apps/joystick/joystick.c:146: error 78: incompatible types
from type 'char xdata\* xdata'
  to type 'int generic\* pdata'
apps/joystick/joystick.c:148: error 78: incompatible types
from type 'char xdata\* xdata'
  to type 'int generic\* pdata'
apps/joystick/joystick.c:150: error 78: incompatible types
from type 'char xdata\* xdata'
  to type 'int generic\* pdata'
make: **\* [apps/joystick/joystick.rel] Error 1

---

-- removed from apps the joystick app

---

Compiling apps/shiftbrite/shiftbrite.rel
apps/shiftbrite/shiftbrite.c:127: error 2: Initializer element is not constant
apps/shiftbrite/shiftbrite.c:128: error 2: Initializer element is not constant
apps/shiftbrite/shiftbrite.c:129: error 2: Initializer element is not constant
make: **\* [apps/shiftbrite/shiftbrite.rel] Error 1

---

-- removed from apps the shiftbrite app

---

Compiling apps/xBridge2/xBridge2.rel
apps/xBridge2/xBridge2.c:1716: warning 212: support for large long long literals is incomplete
apps/xBridge2/xBridge2.c:1716: warning 212: support for large long long literals is incomplete
allocated more than 4 or 0 registers for type longlong-int fixed
allocated more than 4 or 0 registers for type longlong-int fixed
allocated more than 4 or 0 registers for type longlong-int fixed
allocated more than 4 or 0 registers for type longlong-int fixed
allocated more than 4 or 0 registers for type longlong-int fixed
allocated more than 4 or 0 registers for type longlong-int fixed
apps/xBridge2/xBridge2.c:1800: error 226: no type specifier for '(cast)'
make: **\* [apps/xBridge2/xBridge2.rel] Error 1

---

-- modified memcpy(&settings, (__xdata *)FLASH_SETTINGS, sizeof(settings));
-- to memcpy(&settings, (uint8 XDATA *)FLASH_SETTINGS, sizeof(settings));

---

Compiling apps/xBridge3/xBridge3.rel
apps/xBridge3/xBridge3.c:1710: warning 212: support for large long long literals is incomplete
apps/xBridge3/xBridge3.c:1710: warning 212: support for large long long literals is incomplete
allocated more than 4 or 0 registers for type longlong-int fixed
allocated more than 4 or 0 registers for type longlong-int fixed
allocated more than 4 or 0 registers for type longlong-int fixed
allocated more than 4 or 0 registers for type longlong-int fixed
allocated more than 4 or 0 registers for type longlong-int fixed
allocated more than 4 or 0 registers for type longlong-int fixed
apps/xBridge3/xBridge3.c:1794: error 226: no type specifier for '(cast)'
make: **\* [apps/xBridge3/xBridge3.rel] Error 1

---

-- modified memcpy(&settings, (__xdata *)FLASH_SETTINGS, sizeof(settings));
-- to memcpy(&settings, (uint8 XDATA *)FLASH_SETTINGS, sizeof(settings));

---

Compile OK (I get only the above non blocking warnings)

**Comment by jstevensog** [comment]
Hello,
Sorry for the long delay in replying.  The issue appears to be that you are using an SDCC version far in advance of what the wixel build tool uses, and the SDK is built against.  I get no compile errors at all using the standard wixel build tools, which includes version 3.1.0 of SDCC (Nov 22, 2011).
I suggest you source that SDCC version and try building against a clean version of my wixel SDK.  You cannot use the standard Pololu wixel SDK to build xBridge, et al.
Cheers
